#Literatura e Outros Escritos

## A fogueira das vaidades
<div style="text-align: justify">Esta obra literária de Tom Wolfe, prefaciada por ninguém menos que Paulo Francis, que diz que essa obra mudou a natureza dos romances americanos. Mostra o mundo dourado e glamuroso  dos “yuppies” nova iorquinos, operadores de Wall Street cujo símbolo é o enorme touro e sua força reprodutora,  valentia e ousadia. Define tais personagens como de “alta wattagem social”. Assim é o mercado de capitais onde na mesma velocidade que se constroem fortunas, fama e sucesso também se  destroem fortunas e reputações, e faz uma alegoria de   seus atores que  hoje estão no alto do “pau de sebo” mas  podem a qualquer momento escorregar vertiginosamente para o mesmo ponto de onde iniciaram a escalada: o chão, o solo onde vão rastejar saudosos dos tempos de bonança e fausto. Curioso que eu não sabia da existência do pau de sebo na cultura americana. Achava que era coisa caipira, só nossa.     
Na história, Shermann Mc Coy trabalha num banco internacional de investimentos que ocupa nada menos do que 5 andares de um luxuoso prédio comercial em plena Wall Street. Façanha que não é para poucos mortais pois a maioria de seus operadores trabalha em pequenas salas alugadas. O filme é carregado de ironias e vocês já devem ter percebido a minha predileção por elas.    
Shermann exemplifica  muito bem o “yuppie” realizado à custa do sucesso na carreira profissional como operador da bolsa mais famosa e importante do mundo. Mora na Park Avenue, tem uma bela esposa, filha que estuda em colégio tradicional e de quebra uma amante estonteante. Tem uma Mercedez esportiva mas, quando vai à uma festa a apenas alguns quarteirões de sua residência, que poderiam ser vencidos a pé em poucos minutos, e aí vem a ironia: aluga uma limusine para chegar em grande estilo. As mulheres são descritas como “raio x ambulante” pois de tanto malhar seus decotes mostram os ossos que saltam à vista e ainda faz a ferina observação de que se colocasse um prumo na parte posterior da cabeça das mulheres, a parte de baixo do pêndulo não resvalaria na respectiva bunda, por falta de recheio. Mais ferinamente ainda critica o “american way of life” que só aceita a casta especial  que ele cunhou de WASPs: White, anglo saxão e protestante. Os negros e amarelos  são párias, a escória. Shermann se envolve em um acidente de automóvel, quando enlevado com a companhia da estonteante amante, também casada,  cai por engano em uma zona perigosa do Bronx onde atropela fatalmente  um garoto negro que salta à frente de seu carro esportivo. Tudo desmorona naquela vida de sonhos, a verdadeira “Fogueira das Vaidades” e  começa aí a queda vertiginosa do pau de sebo. Parcelas altíssimas do financiamento do luxuoso apartamento na Park Avenue, a mais exclusiva das avenidas nova iorquinas, onde morou inclusive o beattle John Lennon, o carro esportivo financiado mais escola particular da filha, despesas de condomínio, academia, roupas  de grife e vida de luxo da mulher somados à um processo criminal marcam a derrocada do antes próspero e bem sucedido operador de obrigações de Wall street. Wolfe descreve também magistralmente a rotina dentro dos corredores do Forum Criminal da temida Justiça americana. Interessante quando um advogado orienta um cliente  para se apresentar perante o juiz. Esse rapaz, que não tem ocupação e vive às custas das mesadas da mãe se apresenta no escritório com um par de tênis estalando de novo, agasalho de grife com a indefectível touca enterrada na cabeça, topete erguido   e com um andar bamboleante que Wolfe descreve como “ginga de cafetão”. O advogado o faz caminhar dentro da sala e analisando sua performance o faz ver que com aquele figurino assim que adentrasse a sala do júri já estaria condenado. Muda então o seu figurino radicalmente e o faz treinar a andar com as mãos entrelaçadas nas costas para eliminar a “ginga de cafetão” e  entrar de cabeça abaixada para passar ao julgador a imagem de menino pobre do gueto, humilde e  marginalizado, vítima do sistema, digno de pena. Tom Wolfe aborda ainda o poder das Igrejas que mantém seu reinado à custa dos mais pobres, à exemplo da série GreenLeaf da Netflix. A mãe do garoto de posse da placa do carro que atropelou e matou seu filho procura o reverendo Bacon de uma dessas igrejas e este se aproveita do episódio para cutucar a sociedade, o prefeito e o poder da supremacia branca. Wolfe critica ainda o sistema habitacional, com a dificuldade dos mais pobres em obter moradia e hoje, conhecendo a história de Donald Trump que herdou do pai milhares de unidades residenciais com fins locatícios e que, à priori desprezava os cadastros dos candidatos negros e não WASPs. Não sei se é intencional mas na época em que escreveu o livro Trump já era o rei desse mercado lucrativo. Enfim, descreve com grande lucidez tanto a vida do gueto quanto a vida glamorosa e fútil na famosa Tribeca: The Triangle Behind the Chanel.     
Tom Wolfe chama pessoas dúbias de morcegos e explica a origem da alcunha: Os morcegos durante uma guerra entre os mamíferos e os pássaros declarou-se mamífero porquê tem dentes e ficou do lado dos que estavam ganhando a guerra. Quando os pássaros começaram a ganhar a guerra o morcego se declarou um deles porquê tinha asas e sabia voar. Por isso não sai durante o dia para que ninguém descubra a dualidade da sua formação genética. Ou seja: não quer que ninguém veja as suas duas máscaras.

## Frases epistolares
<div style="text-align: justify">De todos os livros que li, e alguns fiz até resenhas pelo puro prazer de registrar aquilo que me impressionou naquele momento da leitura. Dessas leituras  somando-se à leitura regular e quase religiosa da revista Veja há mais de cinquenta anos fui pinçando frases que, parafraseando Millor Fernandes, considero como *definições definitivas*. Vamos lá:

**ABRAHM LINCONL**

1) Pode-se enganar alguns por muito tempo ou todos por algum tempo.  Não se pode enganar todos por todo o tempo

**ADAM SMITH**

1) Em condições de absoluta harmonia e entendimento nunca se viu dois cães trocarem seus respectivos ossos

**ANTONIO CARLOS JOBIM**

1)  A cerveja locupleta os vazios da alma.    
2)  É  preciso lutar pela adequada perfusão dos corpos cavernosos.    
3)  Cada canção com nome de mulher que fiz foi uma moça que eu não comi.    
4)  Troco qualquer sinfonia de Beethoven por uma boa ereção.
5)  O sucesso gera o antagonismo.
    
Curiosidades sobre o personagem Tom Jobim:

Lígia, título da famosa canção não foi uma paixão que inspirou a composição mas uma mulher cuja beleza o impressionou bem como os demais frequentadores do Veloso (depois Garota de Ipanema) e acabou se casando com Fernando Sabino, o escritor.
Ainda nesta canção Tom usa a linguagem  da negação que se transforma em afirmação: 
“Eu nunca sonhei com você, nunca fui ao cinema, não gosto de samba, não vou a Ipanema, não gosto de chuva, nem gosto de sol............................... Eu nunca quis tê-la ao meu lado num fim de semana  um chopp gelado em Copacabana, andar pela praia até o Leblon”.................................

**FRANK SINATRA**

1)  Noventa por cento de tudo que ganhei gastei com jogo, mulheres e bebidas. Os dez por cento restantes ficaram para o garçom.    
2)  Ava Gardner é o  mais belo animal sobre a face da terra.     
3)  Só se vive uma vez na vida mas, da maneira como vivo, uma só vez basta. (O Degas aqui concorda em gênero, número e grau)    

**TIM MAIA**

1)  Não bebo, não cheiro e não fumo, mas, às vezes, minto um pouquinho.    
2)  A minha cornitude existencial me inspirou a fazer algumas das minhas melhores canções. (A frase original é de Antonio Maria)    

**JORGE AMADO**

1)  É impossível comer todas as mulheres do mundo, mas deve-se fazer uma tentativa.    

**EISENHOWER**

1)  O mundo pertence aos otimistas. Os pessimistas são meros espectadores.    

**ÉLIO GASPARI**

1)  Havia mais gente comendo o bolo do que amassando a farinha.

**GERALDO ALCKMIN**

1)  A esperteza demais come o esperto

**ROBERTO CAMPOS**

1)  Se tivesse escrito um capítulo amoroso teria apenas uma frase: Nunca fui veado. E uma nota de rodapé: Nem atleta sexual.

**VICTOR HUGO**

 1) Amar outra pessoa é como ver a face de Deus. O amor é o jardim dos jovens.

**MÁRIO DE ANDRADE**

1)  As pessoas não debatem conteúdos, apenas os rótulos. Tenho pressa. Quero a essência.

**NÉLIDA PIÑON**

 1) Sobre Lili Marinho: Ela dosava ironia e inteligência. Tinha elegância moral

**NELSON RODRIGUES**

1)  Só o gênio enxerga o óbvio.

**MÁRIO COVAS** 

1)  Não são todos os políticos que são malandros. Todos malandros é que são iguais.    
2)  Ovo de galinha tem muito mais valor que ovo de ganso. Mas é por causa do estardalhaço que a galinha faz ao por o seu ovo. (Uma referência  a certos políticos que quase nada realizam  mas fazem um barulhão danado para parecer que fizeram  muita coisa)    

**PERRY WHITE** 

1)  O homem é um animal político mas, o homem político é um animal. 

**DOUTEL DE ANDRADE**

1)  Maluco é igual relógio parado. Duas vezes por dia está certo.

**AUGUSTO BOAL** – em Tempo de Guerra

1)  Paz na terra aos homens de boas maneiras 

**ANÔNIMOS**

1) É difícil ensinar truque novo prá cachorro velho.     
2)  O dinheiro só é bom quando não faz falta.    
3)  É o mesmo que economizar palito de dentes  em banquete.     
4)  Si hay pasteles de carne, pero no hay carne, alguna cosa lo hay.    
5)  Se cabritos tem para vender e cabras não  tem, de algum lugar vem.    
6)  Os homens usam o casamento para obter o sexo. Já as mulheres usam o sexo para obter o casamento.    
7)  O casamento é o único tipo de guerra em que você dorme com o inimigo.    
8)  Sou como arroz branco, sirvo apenas para dar mais destaque a pratos mais requintados.    
9)  Sorriso de gato que acabou de comer o canário.    
10) É tão difícil quanto pesar sapos em uma balança.    
11) Antes eu não era perfeito: faltava-me a modéstia.    
12) Discurso tem que ser igual a vestido: nem curto que escandalize e nem longo que entristeça.    
13) Ele quer bancar o Tiradentes com o nosso pescoço.    
14) O gato que persegue dois ratos fica sem nenhum.    
15) Primeiro ponha o cérebro para pensar. Depois a língua para funcionar.    
16) Quem monta no lombo do tigre acaba dentro da barriga do bicho.    
17) Se pensar, não fale. Se falar, não escreva. Se escrever não assine. Se pensar, falar, escrever e assinar depois não se surpreenda.    
18) Ranieri Mazilli era igual absorvente: Estava no melhor lugar nos piores dias, afim de evitar derramamento de sangue.    
    
##Textos garimpados aleatoriamente

<div style="text-align: justify">Quando vejo e leio um texto que me impressiona, trato logo de registrá-lo em meus manuscritos e arquivos, mesmo sabendo que talvez nem tenha a oportunidade de comentar ou ler para alguém mas, mesmo assim tenho dó de deixá-lo perdido e esquecido. Seguem alguns desse registros:
	
**GLORINHA KALIL: SER CHIQUE**

Interessante que *chique* pronunciado aqui em Salto bem acaipirado virou moda, mas de tanto ser usado para coisas bobas se tornou até meio banal e saturado.    
Mas Glorinha o redefine e o coloca no seu merecido pedestal. Vamos lá:

Nunca o termo chique foi tão usado para qualificar pessoas como nos dias de hoje.    
A verdade é que ninguém é chique por decreto. E algumas coisas da vida, infelizmente não estão à venda. Elegância é uma delas.    
Assim, para ser chique é preciso muito mais que um guarda-roupa ou closet recheado de grifes famosas e importadas. Muito mais que um belo carro italiano.      
O que faz uma pessoa chique não é o que essa pessoa usa mas a forma como ela se comporta perante a vida.     
Chique mesmo é ser discreto.    
Quem não procura chamar a atenção com suas risadas muito altas, nem por seus imensos decotes e nem precisa contar vantagens, mesmo quando estas são verdadeiras.    
Chique é atrair, mesmo sem querer, todos os olhares, porque se tem brilho próprio.    
Chique mesmo é ser discreto, não fazer perguntas ou insinuações inoportunas, nem procurar saber o que não é da sua conta.     
Chique é evitar se deixar levar pela mania nacional de jogar lixo na rua.      
Chique mesmo é dar Bom Dia ao porteiro do seu prédio e às pessoas que estão no elevador.      
Chique é lembrar-se do aniversário dos amigos.    
Chique mesmo é não se exceder jamais!    
Nem na bebida, nem na comida, nem na maneira de se vestir.    
Chique mesmo é olhar nos olhos do seu interlocutor.    
Chique mesmo é desligar o “radar”, o “telefone”, quando estiver sentado na mesa do restaurante, prestar verdadeira atenção aos seus companheiros.    
Chique mesmo é honrar a sua palavra, ser grato a quem o ajuda, correto com quem você se relaciona e honesto nos seus negócios.    
Chique mesmo é não fazer a menor questão de aparecer, ainda que você seja o homenageado da noite.     
Chique do chique é não se iludir com “trocentas” plásticas mesmo quando não se pretende corrigir o caráter: não há plástica que salve grosseria,     incompetência, mentira, fraude, agressão, intolerância, ateísmo....... falsidade.     
Mas, para ser chique, chique mesmo, você tem, antes de tudo, de se lembrar sempre de o quão breve é a vida e de que, ao final e ao cabo, vamos todos terminar da mesma maneira, mortos sem levar nada material deste mundo.     
Portanto não gaste sua energia com o que não tem valor, não desperdice as pessoas interessantes com  quem se encontrar e não aceite, em hipótese alguma, fazer qualquer coisa que não lhe faça bem, que não seja correta.     
Lembre-se: o diabo parece chique, mas o inferno não tem qualquer glamour!    
Porquê, no final das contas, chique mesmo é crer em Deus!    
Investir em conhecimento pode nos tornar sábios...... mas, Amor e Fé nos tornam humanos.

**MAX GERINGHER**

O consultor especializado em relações do trabalho e que apresentou quadros inseridos na programação da Globo, faz uma análise perfeita do ambiente de trabalho, seus desdobramentos, seus erros e falhas e enfim traça um diagnóstico dessa área tão importante e do inter-relacionamento entre os profissionais que gravitam numa mesma órbita dentro de uma empresa, o que gera ciúmes, competição e rasteiras sem entrar na seara do assédio sexual ou assédio corporativo como prevalência e ditadura dos chefes sobre os seus subordinados. O texto a seguir é uma mostra elaborada num jogo de palavras que recria esse tenso ambiente de trabalho.  

                Em empresas, cada um é cada um

                Para cada um que explica, tem um que não entende.    
                Para cada um que tem certeza, tem um que diz: depende.    
                Para cada um que é grato, tem um que só reclama.    
                Para cada um que se esforça, tem um que vive da fama.    
                Para cada um que acelera, tem um que pisa no freio.    
                Para cada um que aposta, tem um  coluna do meio.    
                Para cada um que pensa, tem um que pensa que pensa.    
                Para cada um que aceita crítica, tem um que acha ofensa.    
                Para cada um que cumprimenta, tem um que não responde.    
                Para cada um que se expõe, tem um que se esconde.    
                Para cada um que elogia, tem um que censura.    
                Para cada um que empurra, tem um que segura.    
                Para cada um que acredita, tem um que duvida.    
                Para cada um com objetivo, tem um com objeção.    
                Para cada um que fala, tem um que pede por escrito.    
                Para cada um com iniciativa, tem um propondo reunião.    
                Para cada um procurando consenso, tem um procurando atrito.    
                Para cada um que se arrisca, tem um que se intimida.    
                Para cada um que é claro, tem um que faz  salameleque.    
                Para cada um que segue em frente, tem  um que pede feed back.    
                Para cada um com foco, tem um que muda de tema.    
                Para cada um que vê a  solução, tem um que só vê problema.    
                Para cada um que tenta, tem um que diz que vai dar errado.    
                Para cada um que erra, tem um que diz que já tinha avisado.    

Eu, que vivi muito nesses ambientes de trabalho confesso que nunca vi uma definição tão ampla e tão elucidativa do meio corporativo. Me debati muito com idéias, tentei implantar novidades e sempre briguei muito, talvez até venha daí o fato de não ter galgado cargos mais altos. Além de briguento e encrenqueiro sempre fui avesso ao “puxa saquismo” mas tenho comigo a certeza de que por onde passei deixei um legado. Foram os meninos que formei, conforme já foi narrado, que passei todos os meus conhecimentos sem medo de sombra ou competição. Nunca deixei de ensinar o *pulo do gato*. Conforme conta a lenda a onça pediu ao gato que ensinasse os seus pulos para ela, que na verdade queria aprender todos para comer o gato mas, este os ensinou menos um. Quando ela quis dar o bote final o gato deu um pulo novo, que ela não conhecia. Disse para o gato: mas esse você não me ensinou. O gato respondeu: eu já sabia das suas intenções por isso não ensinei o *pulo do gato*.    
Tenho um orgulho muito grande de ter tirado esses garotos das posições mais desimportantes na escala hierárquica das empresas e alçá-los em muito pouco tempo a figuras de destaque dentro daquelas empresas. Alguns eram simples *office boys*, outro era aprendiz de mecânico mas eu enxerguei qualidades nessas pessoas e os tirei do obscurantismo e consegui lhes dar relevância e mesmo uma profissão  como o caso que narrei  do Haroldo que, de office boy rejeitado, hoje é um auditor em empresa multinacional.      
Todas essas idiossincracias que o Max Geringher descreve magistralmente nesse texto, espelham as dificuldades que encontrei nas empresas brigando e encarando colegas ciumentos, mentes pessimistas e conservadoras, avessas a mudanças. Cheguei a brigar até com os donos das empresas ou seus diretores, superiores a mim, para impor pontos de vista que sempre defendi ardorosamente. Hoje olho para trás e vejo e entendo o porquê dessa luta com mentes defasadas e desatualizadas e não me arrependo de ter dado murros em ponta de faca para fazer valer os meus objetivos.  

**TEXTO DE MADRE TEREZA DE CALCUTÁ**

                Muitas vezes as pessoas são egocêntricas, ilógicas e insensatas.    
                Perdoe-as assim mesmo.    
                Se você é gentil, as pessoas podem acusá-lo de egoísta e interesseiro.    
                Seja gentil assim mesmo.    
                Se você é um vencedor, terá alguns falsos amigos e alguns inimigos verdadeiros.    
                Vença assim mesmo.    
                Se você é honesto e franco as pessoas podem enganá-lo.    
                Seja honesto assim mesmo.    
                O que você levou anos para construir, alguém pode destruir de uma hora para outra.    
                Construa assim mesmo.    
                Se você tem Paz, é Feliz, as pessoas podem sentir inveja.    
                Seja Feliz assim mesmo.    
                Dê ao mundo o melhor de você, mas isso pode nunca ser o bastante.    
                Dê o melhor de você assim mesmo.    
                Veja você que no final das contas, é entre você e Deus.    
                Nunca foi entre você e as outras pessoas. 

**TEXTO QUE NÃO ME LEMBRO A AUTORIA:**

**PARA REFLETIR: NÃO É COMIGO**

                Esta é uma história sobre 4 personagens: 
                
                Todo Mundo, Alguém, Qualquer Um e Ninguém.  
                Havia um importante e urgente trabalho  a ser feito. 
                Todo Mundo tinha certeza que Alguém o faria.     
                Qualquer Um poderia tê-lo feito mas Ninguém o fez.    
                Alguém zangou-se porque era um trabalho de Todo Mundo.    
                Todo Mundo pensou que Qualquer Um poderia fazê-lo    
                Ao final Todo Mundo culpou Alguém quando 
                Ninguém fez o que Qualquer Um poderia e deveria ter feito.    

**TEXTO QUE ME FOI ENVIADO POR UMA GRANDE AMIGA DE CÉU AZUL-PR,  ROSA ROTER em 1/7/80**

                A felicidade é o único bem,    
                O lugar para ser feliz é aqui,    
                O tempo para ser feliz é agora,    
                A maneira de ser feliz é ajudar    
                Os demais a serem felizes.

**O TEXTO A SEGUIR É DE AUTORIA DO DEGAS AQUI, EM SUAS DIVAGAÇÕES MISTURANDO BOTÂNICA COM ALMA, RAÍZES COM PENSAMENTOS:**

**A simetria entre as plantas e a nossa alma**

As árvores tem simetria entre a copa e as suas raízes. Assim sendo onde houver uma ponta de um galho uma raiz o estará acompanhando por debaixo da terra. Ou seja se pudéssemos virar a árvore de ponta cabeça o perímetro de suas raízes seria exatamente igual ao perímetro da copa.    
 A natureza, sabiamente, criou as árvores dessa forma para que haja uma sustentação pelas raízes de toda a copa e também para que as pontas das raízes captem água para as pontas dos galhos simetricamente.     
A aura de cada pessoa também tem simetria com a alma e o coração dessa pessoa.    
Quando você rega uma árvore você joga água diretamente nas suas raízes e este regar vai alimentar as folhas que vão produzir flores e frutos.    
Assim sendo, seguindo o exemplo da natureza se você regar a sua alma e seu coração com pensamentos bons, com amor e com compreensão você estará alimentando a sua aura.    
A sua aura vai resplandecer, vai brilhar muito porquê as suas raízes, assim como as das árvores estarão bem alimentadas, bem regadas com bons sentimentos, com pureza no coração, com o perdão sempre concedido.

**A FELICIDADE E O TEMPO (Anônimo)**

                O meu nome é Felicidade, sou casada com o Tempo       
                Ele é a solução de todos o problemas      
                Ele constrói corações, ele cura machucados, ele vence a tristeza.    
                Juntos, eu e o Tempo tivemos três filhos:    
                A Amizade, a Sabedoria e o Amor.    
                A Amizade brilha como o Sol.    
                A Amizade une as pessoas sem nunca ferir, mas sempre consolar.    
                A filha do meio é a Sabedoria: culta,  íntegra, 
                sempre foi mais apegada ao pai: o Tempo.    
                A Sabedoria e o Tempo andam sempre juntos.    
                O filho caçula é o Amor.    
                Ah, como esse me dá trabalho: é teimoso, às vezes só quer morar em um lugar. 
                Eu vivo dizendo Amor, 
                você foi feito para morar em todos os corações, não em apenas um.    
                O Amor é complexo mas é lindo, muito lindo!    
                Quando Ele começa a fazer estragos eu chamo logo o pai dele, o Tempo,
                E aí o Tempo vem fechando todas as feridas que o Amor abriu.
                E tudo, no final, sempre dá certo, 
                se ainda não deu é porque ninguém chegou ao final!
                Por isso, acredite sempre na Família, acredite no Tempo, 
                na Amizade, na Sabedoria e no Amor.
                Quem sabe eu, a Felicidade não bato à sua porta?????????    
                Palavra de hoje: Tempo, tudo no Tempo de Deus e não no nosso.

**FILHO PREDILETO – ERMA BOMBECK** 

                Certa vez perguntaram à uma mãe qual era o seu filho predileto, 
                aquele que ela mais amava;    
                E ela, deixando entrever um sorriso, respondeu:   
                Nada é mais volúvel que um coração de MÃE;    
                E como MÃE, lhe respondo:    
                O Filho predileto    
                É aquele a quem me dedico de corpo e alma é o  doente até que sare;    
                O que partiu, até que volte;    
                O que está cansado, até que descanse    
                O que está com fome até que se alimente;    
                O que está com sede, até que beba;    
                O que estuda, até que aprenda;    
                O que está com sede, até que beba;    
                O que estuda, até que aprenda;    
                O que está com frio até que se agasalhe;    
                O que não trabalhe, até que se empregue;   
                O que namora, até que case;    
                O que casa, até que conviva;    
                O que é Pai, até que crie;    
                O que prometeu, até que cumpra;    
                O que deve, até que pague;    
                O que chora, até que cale;    
                E já com o semblante bem distante daquele sorriso completou:    
                O que já me deixou......... Até que o reencontre.     

**Chico Xavier**

                Que DEUS não permita que eu perca o ROMANTISMO    
                Mesmo eu sabendo que as rosas não falam    
                Que eu não perca o OTIMISMO    
                Mesmo sabendo que o futuro que nos espera não é assim tão alegre    
                Que eu não perca a VONTADE DE VIVER    
                Mesmo sabendo que a VIDA, é em muitos momentos dolorosa;    
                Que eu não perca a vontade de TER GRANDES AMIGOS,    
                Mesmo sabendo que, com as voltas do mundo    
                Estes acabam indo embora de nossas vidas    
                Que eu não perca a vontade de AJUDAR AS PESSOAS    
                Mesmo sabendo que muitas delas são incapazes de ver, 
                reconhecer e retribuir essa ajuda.    
                Que eu não perca o EQUILÍBRIO    
                Mesmo sabendo que inúmeras forças querem que eu caia    
                Que eu não perca a VONTADE DE AMAR    
                Mesmo sabendo que a pessoa que eu mais amo,     
                Pode não sentir o mesmo sentimento por mim    
                Que eu não perca a LUZ e o BRILHO NO OLHAR    
                Mesmo sabendo que muitas coisas que verei no mundo,    
                Escurecerão meus olhos.......    
                Que eu não perca a GARRA     
                Mesmo sabendo que a derrota e a perda    
                São dois adversários extremamente perigosos    
                Que não perca a RAZÃO    
                Mesmo sabendo que as tentações da vida são inúmeras e deliciosas    
                Que eu não perca o SENTIMENTO DE JUSTIÇA     
                Mesmo sabendo que o prejudicado possa ser eu    
                Que eu não perca o meu FORTE ABRAÇO    
                Mesmo sabendo que um dia meus braços estarão fracos    
                Que eu não perca a BELEZA E A ALEGRIA DE VER    
                Mesmo sabendo que muitas lágrimas brotarão dos meus olhos     
                E escorrerão por minha alma.......    
                Que eu não perca o AMOR POR MINHA FAMÍLIA    
                Mesmo sabendo que muitas vezes me exigiria    
                Esforços incríveis para manter a sua HARMONIA    
                Que eu não perca a vontade de doar este ENORME AMOR    
                Que existe em meu coração    
                Mesmo sabendo que muitas vezes ele será submetido e até rejeitado    
                Que eu não perca a vontade de ser GRANDE     
                Mesmo sabendo que o mundo é pequeno    
                E acima de tudo...........     
                Que eu jamais esqueça que deus me ama infinitamente     
                Que um pequeno grão de alegria e esperança dentro de cada um     
                É capaz de mudar e transformar qualquer coisa, pois........    
                A vida é construída nos sonhos    
                E concretizada no amor.

                AMOROSAMENTE,    

                Francisco Cândido Xavier    
